version: '3'

services: 
  nginx:
    build: .
    image: jocbarbosa/node-app
    container_name: node-app-upload
    ports: 
      - "3000:3000"
    networks:
      - local-network
networks: 
  local-network:
    driver: bridge